### ISSUE TITLE
Put markers on actual route.legs start and end location

### ISSUE THREAD

**Issue by thomasjwilliam** [andreyh13/geo-ws#52]
Currently directions route start/end is set by geocoded waypoints. However that logic breaks when routing to/from a route segment that carries the place_id from its "parent" route.
![screenshot 2016-10-20 at 15 44 07](https://cloud.githubusercontent.com/assets/1510602/19562352/44cf400a-96dc-11e6-989c-3b965e1adf73.png)

Directions from Badalona to Av Diagonal Les Corts
https://maps.googleapis.com/maps/api/directions/json?origin=badalona&destination=av%20diagonal%20les%20corts&key=YOUR_KEY

The "native" directions renderer marks start/end by the route.legs[0].start_location and route.legs[legs.length-1].end_location.
http://jsbin.com/yasurikiku/1/edit?html,output

**Comment by andreyh13** [comment]
This issue is fixed.
