### ISSUE TITLE
Feature Request: Add a link to a Static Map that represents the overview_polyline for Directions API calls

### ISSUE THREAD

**Issue by bernalj** [andreyh13/geo-ws#6]
In order to visually check the response of a Directions API response, it would be great to have a link to a Static Map that shows the overview_polyline (i.e. https://maps.googleapis.com/maps/api/staticmap?size=400x400&path=weight:3%7Ccolor:blue%7Cenc:POLYLINE_DATA)

**Comment by andreyh13** [comment]
Directions API overview_polyline visualization is already implemented using Maps JavaScript API.
